- name: reconfigure eos
  block:
    - name: retrieve current config
      ansible.builtin.command: Cli -p 15 -c "show running-config"
      changed_when: false
      register: running_config
      check_mode: no

    - name: retrieve deployed config
      ansible.builtin.command: Cli -p 15 -c "copy flash:ddix-config terminal:"
      changed_when: false
      register: deployed_config
      check_mode: no

    - name: test for pending changes
      ansible.utils.fact_diff:
        before: '{{ running_config.stdout_lines[2:]|reject("match", "^(!|$)") }}'
        after: '{{ deployed_config.stdout_lines[1:-1]|reject("match", "^(!|\s*$)") }}'
      register: config_diff

    - name: replace running config
      ansible.builtin.command: Cli -p 15 -c "configure replace flash:ddix-config"
      when: config_diff.changed
      register: configure
      changed_when: true
      notify: notify about eos changes
  rescue:
    - name: notify about eos failure
      ansible.builtin.uri:
        url: "{{ secrets.matrix.alerts_room_url }}"
        method: POST
        body_format: json
        body:
          msgtype: m.text
          format: org.matrix.custom.html
          body: |
            ❌ **EOS Failure {{ inventory_hostname_short }}**

            Error while {{ ansible_failed_task.name }}:
              {{ ansible_failed_result.msg|indent(2) }}
          formatted_body: |
            <h1>❌ EOS Failure <code>{{ inventory_hostname_short }}</code></h1>
            <ul>
              <li>Error while {{ ansible_failed_task.name }}:
                <pre>{{ ansible_failed_result.msg|e }}</pre>
              </li>
            </ul>
        follow_redirects: no
      delegate_to: localhost
      failed_when: false
      when: secrets.matrix.alerts_room_url is defined

    - name: stop on error
      ansible.builtin.fail:
