#!/usr/bin/env ansible-playbook

- name: commit bird changes
  hosts: bird
  roles:
    - role: bird_commit
  tags:
    - bird

- name: save eos config
  hosts: eos
  remote_user: root
  roles:
    - role: eos_save
  vars:
    ansible_network_os: "{{ engage_network_os }}"
  tags:
    - eos
