#!/usr/bin/env ansible-playbook

- name: Build sflow meta.yml
  hosts: localhost
  roles:
    - sflow_build
  tags:
    - build
    - sflow_build
    - sflow

- name: Build bird.conf
  hosts: localhost
  roles:
    - bird_build
  tags:
    - build
    - bird_build
    - bird

- name: Build eos config
  hosts: localhost
  roles:
    - eos_build
  tags:
    - build
    - eos_build
    - eos

- name: Build RDNS zone files
  hosts: localhost
  roles:
    - rdns_build
  tags:
    - build
    - rdns_build
    - rdns


- name: Push sflow config
  hosts: sflow
  roles:
    - sflow_push
  vars:
    ansible_user: ixp-deploy
  tags:
    - push
    - sflow_push
    - sflow

- name: Push bird config
  hosts: bird
  serial: 1
  any_errors_fatal: true
  roles:
    - bird_push
  tags:
    - push
    - bird_push
    - bird

- name: Push eos config
  hosts: eos
  serial: 1
  any_errors_fatal: true
  roles:
    - eos_push
  vars:
    ansible_user: root
  tags:
    - push
    - eos_push
    - eos

- name: Push RDNS zone files
  hosts: rdns
  roles:
    - rdns_push
  vars:
    ansible_user: ixp-deploy
  tags:
    - push
    - rdns_push
    - rdns


- name: Reload bird
  hosts: bird
  serial: 1
  any_errors_fatal: true
  roles:
    - role: bird_reload
      when: engage_config|default(False)|bool
  tags:
    - engage
    - bird_engage
    - bird

- name: Enable eos config
  hosts: eos
  remote_user: root
  serial: 1
  any_errors_fatal: true
  roles:
    - role: eos_configure
      when: engage_config|default(False)|bool
  tags:
    - engage
    - eos_engage
    - eos

- name: Reload named
  hosts: rdns
  roles:
    - role: rdns_reload
      when: engage_config|default(False)|bool
  vars:
    ansible_user: ixp-deploy
  tags:
    - engage
    - rdns_engage
    - rdns
